version: '2'
services:
    bookservice-app:
        image: bookservice
        external_links:
            - bookservice-mysql:mysql
            - ppc-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - PPC_SLEEP=10 # gives time for the database to boot before the application
    bookservice-mysql:
        extends:
            file: mysql.yml
            service: bookservice-mysql
    ppc-registry:
        extends:
            file: ppc-registry.yml
            service: ppc-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
