version: '2'
services:
    bookservice-mysql:
        container_name: bookservice-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/ppc/bookservice/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=bookservice
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
