version: '2'
services:
    jhipster-registry:
        container_name: ppc-registry
        image: ppc/ppc-registry:v2.5.3
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the PPC Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the config from a git repository
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SECURITY_USER_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
        ports:
            - 8761:8761
