# Common configuration shared between all applications
configserver:
    name: Docker PPC Registry
    status: Connected to the PPC Registry running in Docker

ppc:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8080/eureka/
